import { prisma } from "@/lib/prisma";
import { deleteCloudinaryAssets } from "@/lib/utils/cloudinary.server";

type ExcludeOptions = {
  // The product currently being edited/deleted. Its own (already
  // overwritten, or about-to-be-deleted) reference to a publicId doesn't
  // count as "still in use" — every OTHER product/user does.
  excludeProductId?: string;
  // Same idea for the user currently being edited/deleted (avatar).
  excludeUserId?: string;
};

/**
 * True if `publicId` is still referenced by any Product.images or any
 * User.avatar in the database — other than the record named in `exclude`,
 * whose own reference is the one being replaced/removed right now and so
 * doesn't count.
 *
 * publicIds are generated by Cloudinary itself on upload (see the
 * product-image/avatar upload routes — we never pass our own `public_id`),
 * so under normal use two different records never end up pointing at the
 * same asset by accident. This check exists as a safety net regardless of
 * *how* a publicId might end up shared — a race between two concurrent
 * edits, a future "duplicate product" feature that copies an image by
 * reference instead of re-uploading, a manual data fix, etc. — rather than
 * assuming today's upload flow is the only way data can ever look.
 */
export async function isCloudinaryAssetInUse(
  publicId: string,
  exclude: ExcludeOptions = {}
): Promise<boolean> {
  const [productMatch, userMatch] = await Promise.all([
    prisma.product.findFirst({
      where: {
        images: { some: { publicId } },
        ...(exclude.excludeProductId ? { id: { not: exclude.excludeProductId } } : {}),
      },
      select: { id: true },
    }),
    prisma.user.findFirst({
      where: {
        avatar: { is: { publicId } },
        ...(exclude.excludeUserId ? { id: { not: exclude.excludeUserId } } : {}),
      },
      select: { id: true },
    }),
  ]);

  return Boolean(productMatch || userMatch);
}

/**
 * The safe entry point for cleaning up Cloudinary assets that a
 * product/profile edit or deletion just stopped referencing. Unlike calling
 * deleteCloudinaryAssets directly, this first re-checks the database and
 * silently skips (never deletes) any publicId that's still referenced
 * elsewhere — so one product's edit can never take down an image another
 * product or profile still relies on.
 */
export async function deleteOrphanedCloudinaryAssets(
  publicIds: Array<string | null | undefined>,
  exclude: ExcludeOptions = {}
): Promise<void> {
  const candidates = [...new Set(publicIds.filter((id): id is string => Boolean(id)))];
  if (!candidates.length) return;

  const inUseFlags = await Promise.all(candidates.map((id) => isCloudinaryAssetInUse(id, exclude)));
  const orphaned = candidates.filter((_, index) => !inUseFlags[index]);
  const skipped = candidates.filter((_, index) => inUseFlags[index]);

  if (skipped.length) {
    console.info(
      `Skipped deleting ${skipped.length} Cloudinary asset(s) still referenced by another record:`,
      skipped
    );
  }

  await deleteCloudinaryAssets(orphaned);
}

export async function deleteOrphanedCloudinaryAsset(
  publicId: string | null | undefined,
  exclude: ExcludeOptions = {}
): Promise<void> {
  await deleteOrphanedCloudinaryAssets([publicId], exclude);
}
